openapi: 3.0.0
info:
  title: Treetracker Map Config API
  version: '1.2.0'
  description: 'The Map Config API of Greenstand for handling additional information used in the Web Map Client.'
  contact:
    name: Greenstand Support
    email: admin@greenstand.com
  license:
    name: GPL 3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
servers:
  - url: https://{environment}-k8s.treetracker.org/map_config
    variables:
      environment:
        default: dev
        enum:
          - dev     # Development server
          - test    # Test server
          - prod    # Production server
paths:
  '/config':
    get:
      tags:
        - Configuration
      operationId: get-config
      summary: Get all configurations
      description: Get the list of all configurations corresponding to the the Web Map entities.
      parameters: []
      responses:
        '200':
          description: Successfully retrieve the list of configurations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/configuration'
              examples:
                example:
                  $ref: '#/components/examples/ConfigurationGet'
    post:
      tags:
        - Configuration
      operationId: post-config
      summary: Create new configurations
      description: Create a new configuration object.
      parameters: []
      requestBody:
        description: Configuration request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/configurationPostRequest'
            examples:
              example:
                $ref: '#/components/examples/ConfigurationPostRequest'
      responses:
        '200':
          description: Successfully create a new configuration object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    $ref: '#/components/schemas/configuration'
              examples:
                example:
                  $ref: '#/components/examples/ConfigurationPostResponse'
components:
  schemas:
    configuration:
      title: Configuration
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        data:
          type: object
        ref_id:
          type: string
        ref_uuid:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    configurationPostRequest:
      title: Configuration Request
      type: object
      properties:
        name:
          type: string
        data:
          type: object
        ref_id:
          type: string
        ref_uuid:
          type: string
          format: uuid
  examples:
    ConfigurationGet:
      value:
        - id: d198ac90-12f8-4001-9f31-126ed9c6882f
          name: extra-wallet
          data:
            logo_url: https://greenstand.org/fileadmin/37-replant-world/REPLANT_WORLD_LOGO.png
            cover_url: https://greenstand.org/fileadmin/37-replant-world/REPLANT_WORLD_BANNER.jpg
          ref_id: 41311bda-f247-4b38-9746-f7d12446b613
          ref_uuid: 41311bda-f247-4b38-9746-f7d12446b613
          created_at: '2023-08-17T16:33:23.965Z'
          updated_at: '2023-08-17T16:33:23.965Z'
        - id: 4d814518-ea7b-43dd-980c-fe29ec0f943a
          name: extra-planter
          data:
            about: this planter is good
            created_at: '2022-05-26 06:47:14'
          ref_id: '3564'
          ref_uuid:
          created_at: '2022-09-22T03:32:34.129Z'
          updated_at: '2022-09-22T03:32:34.129Z'
    ConfigurationPostRequest:
      value:
        name: Test Config Item
        data:
          prop1: item1
          prop2: item2
        ref_id: '1234'
        ref_uuid: 214609df-7270-4795-ac63-c76c93c38d12
    ConfigurationPostResponse:
      value:
        config:
          id: 591c791e-49a1-4ed5-a2e0-0a69ffb466f8
          name: Test Config Item
          data:
            prop1: item1
            prop2: item2
          ref_id: '1234'
          ref_uuid: 214609df-7270-4795-ac63-c76c93c38d12
          created_at: '2023-11-17T08:30:40.622Z'
          updated_at: '2023-11-17T08:30:40.622Z'